version: '3.9'
services:
  postgres:
    image: postgres:14-alpine
    restart: always
    environment:
      POSTGRES_DB: peerlab
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - 5432:5432
    volumes:
      - db:/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
  web:
    build: .
    depends_on:
      - postgres
    ports:
      - "8080:8080"
    environment:
      DB_HOST: postgres
    volumes:
      - userContent:/app/public/user-content

volumes:
  db: {}
  userContent: {}
