openapi: 3.0.1
info: 
  title: Peerlab API
  version: 1.0.0
servers:
  - url: /api
$import:
  - users/swagger.yml
  - classes/swagger.yml
  - assignments/swagger.yml
  - work/swagger.yml
  - reviews/swagger.yml
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
  schemas:
    ResponseErrors:
      type: object
      properties:
        errors:
          type: array
          items:
            type: object
            required:
              - message
            properties:
              message:
                type: string
                description: Error message
              field:
                type: string
                description: Field (input) of the error message, used in validation errors
security:
  - bearerAuth: [] 