paths:
  /work:
    post:
      summary: Create a new piece of work
      tags:
        - work
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - className
                - asgmntName
                - type
              properties:
                className:
                  type: string
                  description: Class short name
                asgmntName:
                  type: string
                  description: Assignment short name
                type:
                  type: string
                  enum: [pdf, url]
                filename:
                  type: string
                  description: Filename if type is set to 'pdf'
                url:
                  type: string
                  description: URL if type is set to 'url'
      responses:
        '201':
          description: Work Submission Created
          content:
            application/json:
              schema:
                type: string
                format: uuid
                description: Work uuid
        '400':
          description: Invalid Data
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResponseErrors'
        '404':
          description: Class or assignment doesn't exist or the user doesn't have access to it
        $import: swagger/responses.yml
  /work/{work}:
    get:
      summary: Get a work submission
      tags:
        - work
      parameters:
        - in: path
          name: work
          schema:
            type: string
            format: uuid
          required: true
          description: UUID of work submission
      responses:
        '200':
          description: Work data
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Work'
        '400':
          description: Invalid UUID request parameter
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResponseErrors'
        '404':
          description: Work submission doesn't exist or the user doesn't have access to it
        $import: swagger/responses.yml
    put:
      summary: Update a work submission
      tags:
        - work
      parameters:
        - in: path
          name: work
          schema:
            type: string
            format: uuid
          required: true
          description: UUID of work submission
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - type
              properties:
                type:
                  type: string
                  enum: [pdf, url]
                filename:
                  type: string
                  description: Filename if type is set to 'pdf'
                url:
                  type: string
                  description: URL if type is set to 'url'
      responses:
        '200':
          description: Work Submission Created
          content:
            application/json:
              schema:
                type: string
                format: uuid
                description: Work uuid
        '400':
          description: Invalid Data
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResponseErrors'
        '404':
          description: Work submission doesn't exist or the user doesn't have access to it
        $import: swagger/responses.yml
  /work/{work}/file:
    put:
      summary: Uploads a PDF file for a work submission
      tags:
        - work
      parameters:
        - in: path
          name: work
          schema:
            type: string
            format: uuid
          required: true
          description: UUID of work submission
      requestBody:
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                file:
                  type: string
                  format: base64
      responses:
        '200':
          description: PDF file uploaded
        '400':
          description: Invalid file upload
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResponseErrors'
        '404':
          description: Work submission doesn't exist or the user doesn't have access to it
        $import: swagger/responses.yml
components:
  schemas:
    Work:
      type: object
      required:
        - uuid
        - type
        - url
      properties:
        uuid:
          type: string
          format: uuid
          description: Work submission UUID
        userUUID:
          type: string
          format: uuid
          description: UUID of user who submitted the work
        type:
          type: string
          enum: [pdf, url]
        url:
          type: string
          description: URL submitted or URL of pdf
        uploadTime:
          type: string
          format: date-time