name: Linter

on:
  workflow_dispatch:
  pull_request:
    branches: [ main, dev ]

jobs:
  container:
    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2

    - name: Setup Node v14.x
      uses: actions/setup-node@v1
      with:
        node-version: 14.x

    - name: Update npm
      run: npm install -g npm@latest

    - name: Install dependencies
      run: npm ci

    - name: Run Setup
      run: npm run setup:config

    - name: Run Linter
      run: npm run linter:action